# Generated by Django 4.2.6 on 2023-11-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaccretio', '0002_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='subtitle',
            field=models.CharField(default='Default Subtitle', max_length=255),
        ),
    ]
