# Generated by Django 4.2.6 on 2023-11-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaccretio', '0003_jobpost_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='subtitle',
            field=models.CharField(max_length=255),
        ),
    ]
