# Generated by Django 4.2.6 on 2023-11-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaccretio', '0004_alter_jobpost_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(default='This position is remote within India.', max_length=100),
        ),
    ]
