# Generated by Django 4.2.6 on 2023-11-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaccretio', '0005_alter_jobpost_country_alter_jobpost_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerJobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='cover_letters/')),
            ],
        ),
    ]
