# Generated by Django 4.2.6 on 2023-11-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaccretio', '0006_careerjobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerjobapplication',
            name='job_title',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
