# Generated by Django 4.2.6 on 2023-11-23 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theaccretio', '0008_alter_careerjobapplication_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerjobapplication',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
