# Generated by Django 4.2.6 on 2023-11-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaccretio', '0009_careerjobapplication_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerjobapplication',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
