# Generated by Django 4.2.6 on 2023-11-23 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theaccretio', '0010_alter_careerjobapplication_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
