# Generated by Django 4.2.6 on 2023-11-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaccretio', '0011_jobpost_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
