# Generated by Django 4.2.6 on 2024-04-05 08:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theaccretio', '0012_alter_jobpost_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
